-- UUIDs and transaction-stable timestamps cannot prove event order when more
-- than one negotiation action is stored in the same transaction. Give every
-- event a database-assigned monotonic sequence and use it for freshness gates.

alter table public.marketplace_inquiry_offer_events
  add column if not exists event_sequence bigint generated by default as identity;

create unique index if not exists marketplace_inquiry_offer_events_sequence_idx
  on public.marketplace_inquiry_offer_events (event_sequence);

create index if not exists marketplace_inquiry_offer_events_inquiry_sequence_idx
  on public.marketplace_inquiry_offer_events (inquiry_id, event_sequence desc);

create or replace function public.record_buyer_inquiry_response(
  p_inquiry_id uuid,
  p_responding_to_event_id uuid,
  p_buyer_email text,
  p_response text,
  p_amount_minor bigint default null,
  p_note text default null
)
returns table(event_id uuid, inquiry_status text, notification_status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_currency text;
  v_current_status text;
  v_buyer_user_id uuid;
  v_event_type text;
  v_target_status text;
  v_event_id uuid;
  v_notification_status text;
  v_latest_event_id uuid;
  v_target_event_type text;
begin
  if p_response not in ('ACCEPT','COUNTER','DECLINE') then raise exception 'Invalid response'; end if;
  if p_response = 'COUNTER' and (p_amount_minor is null or p_amount_minor <= 0) then
    raise exception 'A positive counteroffer amount is required';
  end if;
  if p_response <> 'COUNTER' and p_amount_minor is not null then
    raise exception 'Amount is only allowed for a counteroffer';
  end if;
  if p_note is not null and char_length(p_note) > 1000 then raise exception 'Response note is too long'; end if;

  select inquiry.currency, inquiry.status, inquiry.buyer_user_id
  into v_currency, v_current_status, v_buyer_user_id
  from public.marketplace_inquiries as inquiry
  where inquiry.id = p_inquiry_id
    and lower(trim(inquiry.buyer_email)) = lower(trim(p_buyer_email))
  for update of inquiry;

  if v_currency is null then raise exception 'Enquiry not found or buyer identity does not match'; end if;

  select event.id, event.seller_notification_status
  into v_event_id, v_notification_status
  from public.marketplace_inquiry_offer_events as event
  where event.inquiry_id = p_inquiry_id
    and event.responding_to_event_id = p_responding_to_event_id
  limit 1;

  if v_event_id is not null then
    return query select v_event_id, v_current_status, v_notification_status;
    return;
  end if;

  if v_current_status in ('WON','LOST','SPAM') then raise exception 'This enquiry is already closed'; end if;

  select event.event_type
  into v_target_event_type
  from public.marketplace_inquiry_offer_events as event
  where event.id = p_responding_to_event_id
    and event.inquiry_id = p_inquiry_id
    and event.event_type in ('SELLER_ACCEPTED_FOR_NEGOTIATION','SELLER_COUNTERED');
  if v_target_event_type is null then raise exception 'Seller response not found or cannot be answered'; end if;

  select event.id into v_latest_event_id
  from public.marketplace_inquiry_offer_events as event
  where event.inquiry_id = p_inquiry_id
  order by event.event_sequence desc
  limit 1;
  if v_latest_event_id is distinct from p_responding_to_event_id then raise exception 'This negotiation link is no longer current'; end if;

  v_event_type := case p_response
    when 'ACCEPT' then 'BUYER_ACCEPTED_FOR_NEGOTIATION'
    when 'COUNTER' then 'BUYER_COUNTERED'
    else 'BUYER_DECLINED'
  end;
  v_target_status := case when p_response = 'DECLINE' then 'LOST' else 'NEGOTIATING' end;

  insert into public.marketplace_inquiry_offer_events (
    inquiry_id, event_type, actor_role, actor_user_id, amount_minor, currency, note,
    buyer_notification_status, seller_notification_status, responding_to_event_id, idempotency_key
  ) values (
    p_inquiry_id, v_event_type, 'BUYER', v_buyer_user_id, p_amount_minor, v_currency,
    nullif(trim(p_note), ''), 'not_required', 'pending', p_responding_to_event_id,
    'buyer-response:' || p_responding_to_event_id::text
  ) returning id, seller_notification_status into v_event_id, v_notification_status;

  update public.marketplace_inquiries
  set status = v_target_status,
      last_activity_at = timezone('utc'::text, now()),
      closed_at = case when v_target_status = 'LOST' then timezone('utc'::text, now()) else null end
  where id = p_inquiry_id;

  return query select v_event_id, v_target_status, v_notification_status;
end;
$$;

revoke all on function public.record_buyer_inquiry_response(uuid, uuid, text, text, bigint, text) from public, anon, authenticated;
grant execute on function public.record_buyer_inquiry_response(uuid, uuid, text, text, bigint, text) to service_role;

comment on column public.marketplace_inquiry_offer_events.event_sequence is
  'Database-assigned event order used for freshness decisions; UUID and transaction timestamps are not ordering evidence.';

comment on function public.record_buyer_inquiry_response(uuid, uuid, text, text, bigint, text) is
  'Service-only atomic buyer response to the latest seller negotiation event, ordered by a monotonic database sequence.';
